services:
  - type: web
    name: jalraksha
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn jalraksha.wsgi:application"
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False
      - key: ALLOWED_HOSTS
        value: .onrender.com
      - key: PYTHON_VERSION
        value: 3.11.0