# Generated by Django 5.2.7 on 2025-10-06 18:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sensors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeakDetection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('severity', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], max_length=20)),
                ('status', models.CharField(choices=[('DETECTED', 'Detected'), ('INVESTIGATING', 'Investigating'), ('CONFIRMED', 'Confirmed'), ('REPAIRED', 'Repaired'), ('FALSE_ALARM', 'False Alarm')], default='DETECTED', max_length=20)),
                ('estimated_loss_rate', models.FloatField(help_text='Liters per hour')),
                ('confidence_score', models.FloatField(help_text='AI confidence 0-1')),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sensors.sensordevice')),
            ],
            options={
                'ordering': ['-detected_at'],
            },
        ),
        migrations.CreateModel(
            name='ConsumptionPattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('total_consumption', models.FloatField(help_text='Liters')),
                ('peak_hour', models.IntegerField()),
                ('continuous_flow_detected', models.BooleanField(default=False)),
                ('anomaly_score', models.FloatField(default=0.0)),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sensors.sensordevice')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('sensor', 'date')},
            },
        ),
    ]
