# Generated by Django 5.2.7 on 2025-10-06 18:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SensorDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=50, unique=True)),
                ('sensor_type', models.CharField(choices=[('FLOW', 'Ultrasonic Flow Sensor'), ('PRESSURE', 'Pressure Sensor')], max_length=20)),
                ('deployment_type', models.CharField(choices=[('MUNICIPAL', 'Municipal Distribution'), ('RESIDENTIAL', 'Residential Society')], max_length=20)),
                ('location', models.CharField(max_length=255)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('installation_date', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('last_maintenance', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WaterConsumptionZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('zone_type', models.CharField(max_length=50)),
                ('contact_person', models.CharField(max_length=100)),
                ('contact_email', models.EmailField(max_length=254)),
                ('contact_phone', models.CharField(max_length=15)),
                ('sensors', models.ManyToManyField(related_name='zones', to='sensors.sensordevice')),
            ],
        ),
        migrations.CreateModel(
            name='SensorReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('flow_rate', models.FloatField(blank=True, help_text='Liters per minute', null=True)),
                ('pressure', models.FloatField(blank=True, help_text='PSI', null=True)),
                ('temperature', models.FloatField(blank=True, help_text='Celsius', null=True)),
                ('battery_level', models.IntegerField(default=100, help_text='Percentage')),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='sensors.sensordevice')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['sensor', '-timestamp'], name='sensors_sen_sensor__d03b31_idx')],
            },
        ),
    ]
